version: '3'
services:
  musical-advisor:
    image: "br.com.cominotti.musical_advisor:0.0.1-SNAPSHOT"
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: docker
    ports:
    - "8080:8080"